const DEFAULT_FIRESTORE_DATABASE_ID = 'clc-dev-db';
const DEFAULT_ORGANIZATION_ID = 'clc-dev';

export const FIRESTORE_DATABASE_ID =
  String(import.meta.env.VITE_FIREBASE_DATABASE_ID || DEFAULT_FIRESTORE_DATABASE_ID).trim() ||
  DEFAULT_FIRESTORE_DATABASE_ID;

export const ORGANIZATION_ID =
  String(import.meta.env.VITE_ORGANIZATION_ID || DEFAULT_ORGANIZATION_ID).trim() ||
  DEFAULT_ORGANIZATION_ID;
