import ComplianceCodeAreaSection from './ComplianceCodeAreaSection.jsx';
import NotAssessedAreasPanel from './NotAssessedAreasPanel.jsx';

export default function ComplianceByCodeAreaPanel({
  openComposerModal,
  complianceCodeAreas,
  requirementsByCodeArea,
  requirementsById,
  availableFindings,
  findingMatchesCodeArea,
  getFindingBucketId,
  expandedCodeAreaIds,
  setExpandedCodeAreaIds,
  filteredFindings,
  overviewFindingScope,
  overviewRequirementFilter,
  setOverviewRequirementFilter,
  overviewFilterRef,
  findingViewFilters,
  setOverviewFilterOpen,
  overviewFilterOpen,
  findingFilterLabelMap,
  toggleFindingViewFilter,
  clearFindingViewFilters,
  findingDecisions,
  expandedOverviewFindingIds,
  setExpandedOverviewFindingIds,
  closingOverviewFindingIds,
  findingSeverityBadgeMap,
  findingEvidenceStrengthMap,
  isLeadFindingByTaxonomy,
  isInspectorAddedFinding,
  buildEvidencePassages,
  safeText,
  formatReferenceText,
  activeMenuFindingId,
  setActiveMenuFindingId,
  findingMenuRef,
  handleRequestFindingDecision,
  handleDeleteFinding,
  handleJumpToRequirement,
  handleViewDocument,
  handleShowGuidance,
  openLeadConfirmModal,
  inlineRejectFindingId,
  inlineRejectReason,
  setInlineRejectReason,
  inlineRejectNote,
  setInlineRejectNote,
  handleConfirmInlineReject,
  setInlineRejectFindingId,
  inlineDismissFindingId,
  inlineDismissReason,
  setInlineDismissReason,
  inlineDismissNote,
  setInlineDismissNote,
  handleConfirmInlineDismiss,
  setInlineDismissFindingId,
  leadConfirmOpen,
  leadConfirmFindingId,
  leadConfirmOriginStep,
  closeLeadConfirmModal,
  launchLeadEvidenceHighlighter,
  notAssessedExpanded,
  setNotAssessedExpanded,
  notApplicableExpanded,
  setNotApplicableExpanded,
  notAssessedAreas,
  notApplicableAreas,
  handleRestoreNotAssessedArea
}) {
  return (
    <section className="panel compliance-code-area-panel">
      <div className="section-heading">
        <h2>Findings by Code Area</h2>
      </div>
      <div className="code-area-list">
        {[...complianceCodeAreas]
          .sort((left, right) => left.name.localeCompare(right.name))
          .map((area) => (
            <ComplianceCodeAreaSection
              key={area.id}
              area={area}
              requirementsByCodeArea={requirementsByCodeArea}
              requirementsById={requirementsById}
              availableFindings={availableFindings}
              filteredFindings={filteredFindings}
              findingMatchesCodeArea={findingMatchesCodeArea}
              getFindingBucketId={getFindingBucketId}
              expandedCodeAreaIds={expandedCodeAreaIds}
              setExpandedCodeAreaIds={setExpandedCodeAreaIds}
              overviewRequirementFilter={overviewRequirementFilter}
              overviewFindingScope={overviewFindingScope}
              setOverviewRequirementFilter={setOverviewRequirementFilter}
              overviewFilterRef={overviewFilterRef}
              findingViewFilters={findingViewFilters}
              setOverviewFilterOpen={setOverviewFilterOpen}
              overviewFilterOpen={overviewFilterOpen}
              findingFilterLabelMap={findingFilterLabelMap}
              toggleFindingViewFilter={toggleFindingViewFilter}
              clearFindingViewFilters={clearFindingViewFilters}
              findingDecisions={findingDecisions}
              expandedOverviewFindingIds={expandedOverviewFindingIds}
              setExpandedOverviewFindingIds={setExpandedOverviewFindingIds}
              closingOverviewFindingIds={closingOverviewFindingIds}
              findingSeverityBadgeMap={findingSeverityBadgeMap}
              findingEvidenceStrengthMap={findingEvidenceStrengthMap}
              isLeadFindingByTaxonomy={isLeadFindingByTaxonomy}
              isInspectorAddedFinding={isInspectorAddedFinding}
              buildEvidencePassages={buildEvidencePassages}
              safeText={safeText}
              formatReferenceText={formatReferenceText}
              activeMenuFindingId={activeMenuFindingId}
              setActiveMenuFindingId={setActiveMenuFindingId}
              findingMenuRef={findingMenuRef}
              handleRequestFindingDecision={handleRequestFindingDecision}
              handleDeleteFinding={handleDeleteFinding}
              handleJumpToRequirement={handleJumpToRequirement}
              handleViewDocument={handleViewDocument}
              openLeadConfirmModal={openLeadConfirmModal}
              inlineRejectFindingId={inlineRejectFindingId}
              inlineRejectReason={inlineRejectReason}
              setInlineRejectReason={setInlineRejectReason}
              inlineRejectNote={inlineRejectNote}
              setInlineRejectNote={setInlineRejectNote}
              handleConfirmInlineReject={handleConfirmInlineReject}
              setInlineRejectFindingId={setInlineRejectFindingId}
              inlineDismissFindingId={inlineDismissFindingId}
              inlineDismissReason={inlineDismissReason}
              setInlineDismissReason={setInlineDismissReason}
              inlineDismissNote={inlineDismissNote}
              setInlineDismissNote={setInlineDismissNote}
              handleConfirmInlineDismiss={handleConfirmInlineDismiss}
              setInlineDismissFindingId={setInlineDismissFindingId}
              leadConfirmOpen={leadConfirmOpen}
              leadConfirmFindingId={leadConfirmFindingId}
              leadConfirmOriginStep={leadConfirmOriginStep}
              closeLeadConfirmModal={closeLeadConfirmModal}
              launchLeadEvidenceHighlighter={launchLeadEvidenceHighlighter}
              openComposerModal={openComposerModal}
               handleShowGuidance={handleShowGuidance}
            />
          ))}
        <NotAssessedAreasPanel
          expanded={notAssessedExpanded}
          setExpanded={setNotAssessedExpanded}
          entries={notAssessedAreas}
          title="Not Assessed"
          emptyText="No code areas skipped by the inspector."
        />
      </div>
    </section>
  );
}
